ALTER TABLE assets
  ADD COLUMN os_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN cpu_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN ram_gb INT DEFAULT NULL,
  ADD COLUMN hdd_size VARCHAR(255) DEFAULT NULL,
  ADD COLUMN last_sync DATETIME DEFAULT NULL,
  ADD COLUMN motherboard_manufacturer VARCHAR(255) DEFAULT NULL,
  ADD COLUMN form_factor VARCHAR(255) DEFAULT NULL,
  ADD COLUMN last_user VARCHAR(255) DEFAULT NULL,
  ADD COLUMN approx_age INT DEFAULT NULL,
  ADD COLUMN performance_score INT DEFAULT NULL,
  ADD COLUMN warranty_status VARCHAR(255) DEFAULT NULL,
  ADD COLUMN warranty_end_date DATE DEFAULT NULL;
