ALTER TABLE staff
  ADD COLUMN street VARCHAR(255) NULL,
  ADD COLUMN city VARCHAR(255) NULL,
  ADD COLUMN state VARCHAR(255) NULL,
  ADD COLUMN postcode VARCHAR(20) NULL,
  ADD COLUMN country VARCHAR(255) NULL,
  ADD COLUMN department VARCHAR(255) NULL,
  ADD COLUMN job_title VARCHAR(255) NULL,
  ADD COLUMN org_company VARCHAR(255) NULL,
  ADD COLUMN manager_name VARCHAR(255) NULL;
