ALTER TABLE shop_products
  ADD COLUMN IF NOT EXISTS buy_price DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS weight DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS length DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS width DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS height DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS stock_at DATE NULL,
  ADD COLUMN IF NOT EXISTS warranty_length VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS stock_nsw INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stock_qld INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stock_vic INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stock_sa INT NOT NULL DEFAULT 0,
  ADD UNIQUE KEY IF NOT EXISTS idx_vendor_sku_unique (vendor_sku);
