CREATE TABLE IF NOT EXISTS pending_staff_access (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    staff_id INT NOT NULL,
    company_id INT NOT NULL,
    staff_permission TINYINT NOT NULL DEFAULT 0,
    can_manage_staff TINYINT NOT NULL DEFAULT 0,
    can_manage_licenses TINYINT NOT NULL DEFAULT 0,
    can_manage_assets TINYINT NOT NULL DEFAULT 0,
    can_manage_invoices TINYINT NOT NULL DEFAULT 0,
    can_manage_office_groups TINYINT NOT NULL DEFAULT 0,
    can_order_licenses TINYINT NOT NULL DEFAULT 0,
    can_access_shop TINYINT NOT NULL DEFAULT 0,
    can_access_cart TINYINT NOT NULL DEFAULT 0,
    can_access_orders TINYINT NOT NULL DEFAULT 0,
    can_access_forms TINYINT NOT NULL DEFAULT 0,
    is_admin TINYINT NOT NULL DEFAULT 0,
    role_id INT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uniq_pending_staff_company (staff_id, company_id),
    CONSTRAINT fk_pending_staff_access_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
    CONSTRAINT fk_pending_staff_access_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pending_staff_access_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
