CREATE TABLE IF NOT EXISTS call_recordings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_path VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  caller_number VARCHAR(50),
  callee_number VARCHAR(50),
  caller_staff_id INT,
  callee_staff_id INT,
  call_date DATETIME NOT NULL,
  duration_seconds INT,
  transcription TEXT,
  transcription_status VARCHAR(50) DEFAULT 'pending',
  linked_ticket_id INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (caller_staff_id) REFERENCES staff(id) ON DELETE SET NULL,
  FOREIGN KEY (callee_staff_id) REFERENCES staff(id) ON DELETE SET NULL,
  FOREIGN KEY (linked_ticket_id) REFERENCES tickets(id) ON DELETE SET NULL,
  INDEX idx_call_date (call_date),
  INDEX idx_caller_staff (caller_staff_id),
  INDEX idx_callee_staff (callee_staff_id),
  INDEX idx_linked_ticket (linked_ticket_id),
  INDEX idx_transcription_status (transcription_status)
);
