ALTER TABLE shop_orders
  ADD COLUMN IF NOT EXISTS shipping_option VARCHAR(30) NOT NULL DEFAULT 'address_on_file',
  ADD COLUMN IF NOT EXISTS shipping_street VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shipping_city VARCHAR(100) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shipping_state VARCHAR(100) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shipping_postcode VARCHAR(20) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS shipping_country VARCHAR(100) NULL DEFAULT NULL;
