-- Configurable per-company dashboards. Personal layouts use user_preferences.
CREATE TABLE IF NOT EXISTS company_dashboard_layouts (
 company_id INT NOT NULL PRIMARY KEY, layout_json JSON NOT NULL, updated_by INT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_dashboard_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
 CONSTRAINT fk_dashboard_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT
);

INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-open-tickets','Dashboard - Open tickets','Dashboard panel: Open tickets.','SELECT id, subject FROM tickets WHERE company_id = {{current.company}} AND status NOT IN (''closed'',''resolved'')',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-tickets-by-status','Dashboard - Tickets by status','Dashboard panel: Tickets by status.','SELECT status AS X, COUNT(*) AS Y FROM tickets WHERE company_id = {{current.company}} GROUP BY status ORDER BY tickets DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-tickets-created-30-days','Dashboard - Tickets created (30 days)','Dashboard panel: Tickets created (30 days).','SELECT DATE(created_at) AS X, COUNT(*) AS Y FROM tickets WHERE company_id = {{current.company}} AND created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(created_at) ORDER BY day',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-assets','Dashboard - Assets','Dashboard panel: Assets.','SELECT id, name FROM assets WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-assets-by-type','Dashboard - Assets by type','Dashboard panel: Assets by type.','SELECT COALESCE(asset_type, ''Other'') AS X, COUNT(*) AS Y FROM assets WHERE company_id = {{current.company}} GROUP BY asset_type ORDER BY assets DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-staff','Dashboard - Staff','Dashboard panel: Staff.','SELECT id, email FROM staff WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-licenses','Dashboard - Licenses','Dashboard panel: Licenses.','SELECT id, name FROM licenses WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-licenses-by-product','Dashboard - Licenses by product','Dashboard panel: Licenses by product.','SELECT COALESCE(product_name, ''Other'') AS X, COUNT(*) AS Y FROM licenses WHERE company_id = {{current.company}} GROUP BY product_name ORDER BY licenses DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-subscriptions','Dashboard - Subscriptions','Dashboard panel: Subscriptions.','SELECT id, name FROM subscriptions WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-invoices','Dashboard - Invoices','Dashboard panel: Invoices.','SELECT id, invoice_number FROM invoices WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-issues','Dashboard - Issues','Dashboard panel: Issues.','SELECT id, title FROM issues WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-issues-by-status','Dashboard - Issues by status','Dashboard panel: Issues by status.','SELECT status AS X, COUNT(*) AS Y FROM issues WHERE company_id = {{current.company}} GROUP BY status',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-orders','Dashboard - Orders','Dashboard panel: Orders.','SELECT id, order_number FROM shop_orders WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-orders-by-status','Dashboard - Orders by status','Dashboard panel: Orders by status.','SELECT status AS X, COUNT(*) AS Y FROM shop_orders WHERE company_id = {{current.company}} GROUP BY status',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-forms','Dashboard - Forms','Dashboard panel: Forms.','SELECT id, name FROM forms WHERE company_id = {{current.company}} OR company_id IS NULL',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-knowledge-articles','Dashboard - Knowledge articles','Dashboard panel: Knowledge articles.','SELECT id, title FROM knowledge_base_articles WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-compliance-checks','Dashboard - Compliance checks','Dashboard panel: Compliance checks.','SELECT id, name FROM compliance_checks WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-compliance-by-status','Dashboard - Compliance by status','Dashboard panel: Compliance by status.','SELECT status AS X, COUNT(*) AS Y FROM compliance_checks WHERE company_id = {{current.company}} GROUP BY status',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-backup-jobs','Dashboard - Backup jobs','Dashboard panel: Backup jobs.','SELECT id, name FROM backup_jobs WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-backup-jobs-by-status','Dashboard - Backup jobs by status','Dashboard panel: Backup jobs by status.','SELECT status AS X, COUNT(*) AS Y FROM backup_jobs WHERE company_id = {{current.company}} GROUP BY status',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-calls-30-days','Dashboard - Calls (30 days)','Dashboard panel: Calls (30 days).','SELECT id, created_at FROM calls WHERE company_id = {{current.company}} AND created_at >= CURRENT_DATE - INTERVAL 30 DAY',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-calls-by-day','Dashboard - Calls by day','Dashboard panel: Calls by day.','SELECT DATE(created_at) AS X, COUNT(*) AS Y FROM calls WHERE company_id = {{current.company}} AND created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(created_at) ORDER BY day',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-quotes','Dashboard - Quotes','Dashboard panel: Quotes.','SELECT id, status FROM quotes WHERE company_id = {{current.company}}',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-quotes-by-status','Dashboard - Quotes by status','Dashboard panel: Quotes by status.','SELECT status AS X, COUNT(*) AS Y FROM quotes WHERE company_id = {{current.company}} GROUP BY status',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-ticket-replies-30-days','Dashboard - Ticket replies (30 days)','Dashboard panel: Ticket replies (30 days).','SELECT tr.id, tr.created_at FROM ticket_replies tr JOIN tickets t ON t.id=tr.ticket_id WHERE t.company_id = {{current.company}} AND tr.created_at >= CURRENT_DATE - INTERVAL 30 DAY',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-ticket-time-by-day','Dashboard - Ticket time by day','Dashboard panel: Ticket time by day.','SELECT DATE(tr.created_at) AS X, SUM(COALESCE(tr.minutes_spent,0)) AS Y FROM ticket_replies tr JOIN tickets t ON t.id=tr.ticket_id WHERE t.company_id = {{current.company}} AND tr.created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(tr.created_at) ORDER BY day',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-global-companies','Dashboard - Global companies','Dashboard panel: Global companies.','SELECT id, name FROM companies',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-global-users','Dashboard - Global users','Dashboard panel: Global users.','SELECT id, email FROM users',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-global-tickets-by-company','Dashboard - Global tickets by company','Dashboard panel: Global tickets by company.','SELECT c.name AS X, COUNT(t.id) AS Y FROM companies c LEFT JOIN tickets t ON t.company_id=c.id GROUP BY c.id,c.name ORDER BY tickets DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-global-assets-by-company','Dashboard - Global assets by company','Dashboard panel: Global assets by company.','SELECT c.name AS X, COUNT(a.id) AS Y FROM companies c LEFT JOIN assets a ON a.company_id=c.id GROUP BY c.id,c.name ORDER BY assets DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-global-staff-by-company','Dashboard - Global staff by company','Dashboard panel: Global staff by company.','SELECT c.name AS X, COUNT(s.id) AS Y FROM companies c LEFT JOIN staff s ON s.company_id=c.id GROUP BY c.id,c.name ORDER BY staff DESC',1);
INSERT IGNORE INTO reporting_queries (slug,name,description,sql_query,is_system) VALUES ('dashboard-notifications','Dashboard - Notifications','Dashboard panel: Notifications.','SELECT id, event_type FROM notifications WHERE user_id IS NOT NULL',1);
