-- Dashboard graphs use an explicit X/Y column contract. Keep the bundled
-- aggregation reports graph-ready for existing installations.
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM tickets WHERE company_id = {{current.company}} GROUP BY status ORDER BY Y DESC' WHERE slug = 'dashboard-tickets-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT DATE(created_at) AS X, COUNT(*) AS Y FROM tickets WHERE company_id = {{current.company}} AND created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(created_at) ORDER BY X' WHERE slug = 'dashboard-tickets-created-30-days' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT COALESCE(asset_type, ''Other'') AS X, COUNT(*) AS Y FROM assets WHERE company_id = {{current.company}} GROUP BY asset_type ORDER BY Y DESC' WHERE slug = 'dashboard-assets-by-type' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT COALESCE(product_name, ''Other'') AS X, COUNT(*) AS Y FROM licenses WHERE company_id = {{current.company}} GROUP BY product_name ORDER BY Y DESC' WHERE slug = 'dashboard-licenses-by-product' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM issues WHERE company_id = {{current.company}} GROUP BY status' WHERE slug = 'dashboard-issues-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM shop_orders WHERE company_id = {{current.company}} GROUP BY status' WHERE slug = 'dashboard-orders-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM compliance_checks WHERE company_id = {{current.company}} GROUP BY status' WHERE slug = 'dashboard-compliance-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM backup_jobs WHERE company_id = {{current.company}} GROUP BY status' WHERE slug = 'dashboard-backup-jobs-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT DATE(created_at) AS X, COUNT(*) AS Y FROM calls WHERE company_id = {{current.company}} AND created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(created_at) ORDER BY X' WHERE slug = 'dashboard-calls-by-day' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT status AS X, COUNT(*) AS Y FROM quotes WHERE company_id = {{current.company}} GROUP BY status' WHERE slug = 'dashboard-quotes-by-status' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT DATE(tr.created_at) AS X, SUM(COALESCE(tr.minutes_spent,0)) AS Y FROM ticket_replies tr JOIN tickets t ON t.id=tr.ticket_id WHERE t.company_id = {{current.company}} AND tr.created_at >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY DATE(tr.created_at) ORDER BY X' WHERE slug = 'dashboard-ticket-time-by-day' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT c.name AS X, COUNT(t.id) AS Y FROM companies c LEFT JOIN tickets t ON t.company_id=c.id GROUP BY c.id,c.name ORDER BY Y DESC' WHERE slug = 'dashboard-global-tickets-by-company' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT c.name AS X, COUNT(a.id) AS Y FROM companies c LEFT JOIN assets a ON a.company_id=c.id GROUP BY c.id,c.name ORDER BY Y DESC' WHERE slug = 'dashboard-global-assets-by-company' AND is_system = 1;
UPDATE reporting_queries SET sql_query = 'SELECT c.name AS X, COUNT(s.id) AS Y FROM companies c LEFT JOIN staff s ON s.company_id=c.id GROUP BY c.id,c.name ORDER BY Y DESC' WHERE slug = 'dashboard-global-staff-by-company' AND is_system = 1;
