-- Expose every Company Overview segment as a standalone Reporting report.
-- Each query is scoped to the company in the viewer's current context and is
-- idempotently seeded as a system report.
INSERT IGNORE INTO reporting_queries (slug, name, description, sql_query, is_system)
VALUES
('report-assets-synced-last-30-days', 'Report - Assets Synced (Last 30 Days)', 'Assets synced during the last 30 days, including device and warranty details.', 'SELECT a.id, a.name, a.type, a.os_name, a.status, a.serial_number, a.last_sync, a.last_user, a.form_factor, a.warranty_status, a.warranty_end_date FROM assets a WHERE a.company_id = {{current.company}} AND a.last_sync >= (CURRENT_DATE - INTERVAL 30 DAY) ORDER BY a.last_sync DESC, a.name ASC', 1),
('report-active-staff', 'Report - Active Staff', 'Enabled staff accounts for the current company.', 'SELECT s.id, COALESCE(NULLIF(s.name, ''''), CONCAT_WS('' '', s.first_name, s.last_name)) AS name, s.email, s.department, COALESCE(s.position, s.job_title) AS job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)', 1),
('report-active-user-accounts', 'Report - Active User Accounts', 'Active company user accounts with Microsoft 365 last sign-in details.', 'SELECT s.id, COALESCE(NULLIF(s.name, ''''), CONCAT_WS('' '', s.first_name, s.last_name)) AS name, s.email, s.department, COALESCE(s.position, s.job_title) AS job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)', 1),
('report-m365-best-practice-summary', 'Report - M365 Best Practice Summary', 'Latest Microsoft 365 best-practice check results for the current company.', 'SELECT r.check_id, r.check_name, r.status, r.details, r.remediation_status, r.run_at FROM m365_best_practice_results r WHERE r.company_id = {{current.company}} ORDER BY CASE r.status WHEN ''fail'' THEN 0 WHEN ''warn'' THEN 1 WHEN ''error'' THEN 2 WHEN ''pass'' THEN 3 ELSE 4 END, r.check_name ASC', 1),
('report-top-mailboxes-by-size', 'Report - Top Mailboxes by Size', 'Top five user and top five shared mailboxes by combined primary and archive storage.', 'SELECT m.display_name, m.user_principal_name, m.mailbox_type, m.storage_used_bytes AS primary_bytes, m.archive_storage_used_bytes AS archive_bytes, COALESCE(m.storage_used_bytes, 0) + COALESCE(m.archive_storage_used_bytes, 0) AS total_bytes FROM m365_mailboxes m WHERE m.company_id = {{current.company}} AND m.mailbox_type IN (''UserMailbox'', ''SharedMailbox'') AND NOT (LOWER(SUBSTR(m.display_name, 1, 8)) = ''package_'') AND (SELECT COUNT(*) FROM m365_mailboxes ranked WHERE ranked.company_id = m.company_id AND ranked.mailbox_type = m.mailbox_type AND COALESCE(ranked.storage_used_bytes, 0) + COALESCE(ranked.archive_storage_used_bytes, 0) > COALESCE(m.storage_used_bytes, 0) + COALESCE(m.archive_storage_used_bytes, 0)) < 5 ORDER BY m.mailbox_type, total_bytes DESC', 1),
('report-orders-this-month', 'Report - Orders This Month', 'Orders placed by the current company during the current calendar month.', 'SELECT so.order_number, so.order_date, so.status, so.shipping_status, so.po_number FROM shop_orders so WHERE so.company_id = {{current.company}} AND so.order_date >= DATE_FORMAT(CURRENT_DATE, ''%Y-%m-01'') AND so.order_date < (CURRENT_DATE + INTERVAL 1 DAY) ORDER BY so.order_date DESC, so.order_number DESC', 1),
('report-licenses', 'Report - Licenses', 'Company licenses with allocated seats, expiry, and renewal details.', 'SELECT l.id, COALESCE(lsn.friendly_name, app.name, l.name) AS license_name, l.count AS total_seats, (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id) AS allocated_seats, GREATEST(l.count - (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id), 0) AS available_seats, l.expiry_date, l.auto_renew, l.notes FROM licenses l LEFT JOIN apps app ON app.vendor_sku = l.platform LEFT JOIN license_sku_friendly_names lsn ON lsn.sku = l.platform WHERE l.company_id = {{current.company}} ORDER BY license_name ASC', 1),
('report-subscriptions', 'Report - Subscriptions', 'Subscriptions linked to the current company.', 'SELECT s.id AS subscription_id, p.name AS product_name, c.name AS category_name, s.quantity, s.status, s.start_date, s.end_date, s.unit_price, s.auto_renew FROM subscriptions s LEFT JOIN shop_products p ON p.id = s.product_id LEFT JOIN subscription_categories c ON c.id = s.subscription_category_id WHERE s.customer_id = {{current.company}} ORDER BY s.status ASC, s.product_name ASC', 1),
('report-essential-8-compliance-progress', 'Report - Essential 8 Compliance Progress', 'Essential 8 requirements and maturity-level compliance for the current company.', 'SELECT ec.name AS control_name, er.maturity_level, er.description AS requirement, COALESCE(cerc.status, ''not_started'') AS status, cerc.notes, cerc.updated_at FROM essential8_requirements er JOIN essential8_controls ec ON ec.id = er.control_id LEFT JOIN company_essential8_requirement_compliance cerc ON cerc.requirement_id = er.id AND cerc.company_id = {{current.company}} ORDER BY ec.id, er.maturity_level, er.requirement_order', 1),
('report-customer-compliance-checks', 'Report - Customer Compliance Checks', 'Active compliance-check assignments and review dates for the current company.', 'SELECT cc.title AS check_title, cat.name AS category_name, a.status, a.next_review_at, a.last_checked_at, a.notes, a.evidence_summary FROM company_compliance_check_assignments a JOIN compliance_checks cc ON cc.id = a.check_id JOIN compliance_check_categories cat ON cat.id = cc.category_id WHERE a.company_id = {{current.company}} AND a.archived = 0 ORDER BY cat.name, cc.sort_order, cc.title', 1),
('report-tickets-past-month', 'Report - Tickets (Past Month)', 'Tickets created for the current company during the past 30 days.', 'SELECT t.id, t.subject, t.status, t.priority, t.category, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND t.created_at >= (CURRENT_DATE - INTERVAL 30 DAY) ORDER BY t.created_at DESC', 1),
('report-asset-custom-field-values', 'Report - Asset Custom Field Values', 'Custom field values recorded against assets belonging to the current company.', 'SELECT a.name AS asset_name, d.name AS field_name, d.field_type, COALESCE(v.value_text, CAST(v.value_boolean AS CHAR), CAST(v.value_date AS CHAR), ''Has value'') AS field_value FROM asset_custom_field_values v JOIN assets a ON a.id = v.asset_id JOIN asset_custom_field_definitions d ON d.id = v.field_definition_id WHERE a.company_id = {{current.company}} ORDER BY d.display_order, d.name, a.name', 1),
('report-issue-tracker-issues', 'Report - Issue Tracker Issues', 'Issue-tracker assignments for the current company.', 'SELECT i.name, i.description, ics.status, ics.notes, ics.updated_at_utc AS updated_at FROM issue_company_statuses ics JOIN issue_definitions i ON i.id = ics.issue_id WHERE ics.company_id = {{current.company}} ORDER BY ics.status, i.name', 1),
('report-backup-history', 'Report - Backup History', 'Backup job events recorded during the past 30 days for the current company.', 'SELECT bj.name AS backup_job, bj.is_active, e.event_date, e.status, e.status_message, e.reported_at FROM backup_jobs bj LEFT JOIN backup_job_events e ON e.backup_job_id = bj.id AND e.event_date >= (CURRENT_DATE - INTERVAL 29 DAY) WHERE bj.company_id = {{current.company}} ORDER BY e.event_date DESC, bj.name ASC', 1),
('report-huntress-edr', 'Report - Huntress EDR', 'Current Huntress EDR incident and signal snapshot.', 'SELECT active_incidents, resolved_incidents, signals_investigated, snapshot_at FROM huntress_edr_stats WHERE company_id = {{current.company}}', 1),
('report-huntress-itdr', 'Report - Huntress ITDR', 'Current Huntress ITDR signal snapshot.', 'SELECT signals_investigated, snapshot_at FROM huntress_itdr_stats WHERE company_id = {{current.company}}', 1),
('report-huntress-security-awareness-training', 'Report - Huntress Security Awareness Training', 'Current Huntress security-awareness learner and phishing metrics.', 'SELECT enrolled_learners, avg_completion_rate, avg_score, phishing_clicks, phishing_compromises, phishing_reports, snapshot_at FROM huntress_sat_stats WHERE company_id = {{current.company}}', 1),
('report-huntress-managed-siem', 'Report - Huntress Managed SIEM', 'Current Huntress Managed SIEM collection snapshot.', 'SELECT data_collected_bytes_30d, window_start, window_end, snapshot_at FROM huntress_siem_stats WHERE company_id = {{current.company}}', 1),
('report-huntress-soc', 'Report - Huntress SOC', 'Current Huntress Security Operations Centre event snapshot.', 'SELECT total_events_analysed, snapshot_at FROM huntress_soc_stats WHERE company_id = {{current.company}}', 1);
