-- Voice monitor configuration is mutable, but attempts are retained as audit
-- records.  Deleting an endpoint therefore nulls attempt.endpoint_id rather
-- than cascading historical results.
CREATE TABLE voice_monitor_endpoints (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id INT NOT NULL,
    subscription_id VARCHAR(36) NULL,
    destination_e164 VARCHAR(32) NOT NULL,
    display_label VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    schedule_cron VARCHAR(128) NULL,
    interval_seconds INT UNSIGNED NULL,
    next_run_at DATETIME(6) NULL,
    timeout_seconds INT UNSIGNED NOT NULL DEFAULT 30,
    max_retries SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    retry_delay_seconds INT UNSIGNED NOT NULL DEFAULT 60,
    expected_behavior ENUM('answer','no_answer','busy','voicemail','any') NOT NULL DEFAULT 'answer',
    transcription_enabled TINYINT(1) NOT NULL DEFAULT 0,
    ticket_on_failure TINYINT(1) NOT NULL DEFAULT 0,
    ticket_failure_threshold SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_voice_monitor_endpoint_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_voice_monitor_endpoint_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL,
    CONSTRAINT chk_voice_monitor_schedule CHECK ((schedule_cron IS NULL) <> (interval_seconds IS NULL)),
    INDEX idx_voice_monitor_due (enabled, next_run_at, id),
    INDEX idx_voice_monitor_company (company_id, enabled, display_label),
    INDEX idx_voice_monitor_subscription (subscription_id)
);

CREATE TABLE voice_monitor_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    endpoint_id BIGINT UNSIGNED NULL,
    company_id INT NOT NULL,
    queued_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at DATETIME(6) NULL,
    answered_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    outcome_status ENUM('queued','dialing','answered','passed','failed','timed_out','cancelled') NOT NULL DEFAULT 'queued',
    provider_response_code VARCHAR(32) NULL,
    provider_call_id VARCHAR(255) NULL,
    failure_category VARCHAR(64) NULL,
    failure_detail VARCHAR(1000) NULL COMMENT 'Sanitized: must not contain provider secrets or raw payloads',
    duration_seconds INT UNSIGNED NULL,
    media_artifact_reference VARCHAR(512) NULL,
    transcript_status ENUM('not_requested','pending','processing','completed','failed') NOT NULL DEFAULT 'not_requested',
    transcript_text_reference VARCHAR(512) NULL,
    retry_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    worker_identity VARCHAR(255) NULL,
    created_ticket_id INT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_voice_monitor_attempt_endpoint FOREIGN KEY (endpoint_id) REFERENCES voice_monitor_endpoints(id) ON DELETE SET NULL,
    CONSTRAINT fk_voice_monitor_attempt_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_voice_monitor_attempt_ticket FOREIGN KEY (created_ticket_id) REFERENCES tickets(id) ON DELETE SET NULL,
    UNIQUE INDEX uq_voice_monitor_provider_call (provider_call_id),
    INDEX idx_voice_monitor_attempt_history (company_id, endpoint_id, queued_at, id),
    INDEX idx_voice_monitor_attempt_reports (company_id, outcome_status, completed_at),
    INDEX idx_voice_monitor_ticket_dedup (company_id, endpoint_id, created_ticket_id, completed_at)
);
