package config

import (
	"strings"
	"testing"
)

func TestParseEnvConfigAcceptsShellStyleValues(t *testing.T) {
	cfg, err := parseEnvConfig(strings.NewReader(`
# generated by RMM
export MYPORTAL_URL="https://portal.example.com"
ENROL_TOKEN='tok123'
AUTO_UPDATE=false
`))
	if err != nil {
		t.Fatalf("parseEnvConfig: %v", err)
	}
	if cfg.PortalURL != "https://portal.example.com" {
		t.Fatalf("PortalURL = %q", cfg.PortalURL)
	}
	if cfg.EnrolToken != "tok123" {
		t.Fatalf("EnrolToken = %q", cfg.EnrolToken)
	}
	if cfg.AutoUpdate {
		t.Fatal("AutoUpdate = true, want false")
	}
}
